### ISSUE TITLE
Вопрос по httptimeshift-ext

### ISSUE THREAD

**Issue by NEKTO606** [Nexterr/simpleTV.youtube#1]
Некстерр, помоги плиз!
В источнике Импульс-тв перестал нормально работать таймшифт. За него, как я понимаю, отвечает скрипт testEvent.lua, но вот что в нем поправить ума не приложу. Выйди на связь пожалуйста!

**Comment by Nexterr** [comment]
на каком канале?
попробуйте заменить testEvent.lua и скрапер Импульс-тв
cloud.mail.ru/public/3jbv/339ZWMsnb

**Comment by NEKTO606** [comment]
Канал Загородный, таймшифт перестал работать в понедельник.
Заменил скрапер, обновил источник, заменил testEvent.lua - проблема осталась.
Когда выбираешь передачу в программе отматывает куда-то назад и ползунок перемотки не работает. С выбором передачи по дате и времени через кнопку Архив таже фигня.
Спасибо тебе за труды!!! Народ страдает без тебя! Возвращайся )))

**Comment by Nexterr** [comment]
обновиите - срапер,скрипт, testEvent

**Comment by NEKTO606** [comment]
Все работает! Спасибо огромное!
