### ISSUE TITLE
проблема с таймшифтом на импульс-тв

### ISSUE THREAD

**Issue by NEKTO606** [Nexterr/simpleTV.youtube#2]
Некстерр, дружище! прости что беспокою, но опять проблема с таймшифтом на импульс-тв. Сегодня обновил расширение из httptimeshift-ext.zip от 24.08.2020. И появился такой баг - если включить передачу по таймшифту, нажать паузу и потом ее отжать, то смещение происходит куда-то в начало передачи. 
Посмотри пожалуйста. Спасибо!

P.S. Канал Загородный.

**Comment by Nexterr** [comment]
там были правки только по яндексу
не могу воспроизвести, выдерживал паузу на несколько секунд  \ минут
подробнее опишите или сделайте видео
проверять лучше на каналах где есть часы рбк, 2х2 итд

при снятии с длинной паузы происходит запрос и может быть несовпадние  +- в несколько секунд

**Comment by NEKTO606** [comment]
Да, проблема была со снятием с длинной паузы, но сегодня ее не получилось воспроизвести, странно. Извиняюсь за ложную тревогу! Еще раз спасибо!
