### ISSUE TITLE
не работает ИмпульсТВ

### ISSUE THREAD

**Issue by NEKTO606** [Nexterr/simpleTV.youtube#3]
Некстерр, привет!
Я опять к вам по поводу импульс-тв. В прошлую пятницу перестали каналы показывать, сегодня попробовал обновить плэйлист - выдает ошибку. Есть надежда на исправление?
Спасибо за труды!

**Comment by Nexterr** [comment]
без понятия, в браузере портал не открывается

**Comment by Nexterr** [comment]
если очень надо
обновите все
введно ограничение на количество регистраций по IP адресу (где-то 5 раз)
либо меняь прокси в скрапере или IP адрес
и вручную обновлять через 7 дней

**Comment by NEKTO606** [comment]
Спасибо большое!
